# File: .github/workflows/set-topic-reusable.yml
name: Set Topic Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The repository name'
        required: true
        type: string
      org:
        description: 'The organization name'
        required: true
        type: string
      github-token:
        description: 'GitHub Token'
        required: true
        type: string
      properties:
        description: 'Properties JSON'
        required: false
        type: string

jobs:
  set-topic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_GITHUB_APP_PRIVATE_KEY }}
          revoke_token: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract Repository Name
        id: extract_repo_name
        run: echo "::set-output name=repo_name::$(echo '${{ github.event.inputs.repo }}' | awk -F'/' '{print $2}')"

      - name: Debug Print received inputs
        run: |
          echo "Received Repo: ${{ github.event.inputs.repo }}"
          echo "Extracted Repo Name: ${{ steps.extract_repo_name.outputs.repo_name }}"
          echo "Received Org: ${{ github.event.inputs.org }}"
          echo "Received Properties: $(echo '${{ github.event.inputs.properties }}' | jq .)"

      - name: Add Topics to Repository
        uses: opencepk/opencepk-module-ghactions-common/github-set-topics@fix/update-gitmodules-action
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          properties-file: '.project-properties.json' # Optional, defaults to .project-properties.json
          repo: ${{ steps.extract_repo_name.outputs.repo_name }}
          org: ${{ github.event.inputs.org }}
          properties: ${{ github.event.inputs.properties }}